### ISSUE TITLE
Unit Vectors

### ISSUE THREAD

**Issue by Sgzanjani1367** [andwatson/interseismic_practical#4]
Hi
What is a U, N, E files format?
Because I have an error in these files and we have them in tiff format.
How can I convert the tiff files to for example E file?

Best regard

**Comment by andwatson** [comment]
Hello, the ENU files are all float32 binary files, same as the vel and vstd files. The ".E" extension here is more informing us of the files content rather than the file type.
LiCSBAS will convert the ENU files from geotiff to float32 in (I think) step 0-2. Otherwise, you could load the geotiffs into python or matlab and export them.
Hope that helps.

**Comment by Sgzanjani1367** [comment]
Thank you very much for your help.
